import React, { createContext, useContext, useState, useEffect } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { buildLocalizedUrl, type AppLanguage } from '@/hooks/useLocalizedNavigate';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    home: 'Home',
    about: 'About Us',
    products: 'Products',
    industrialProducts: 'Industrial Products',
    miningProducts: 'Mining Products',
    privatePort: 'Private Port',
    financial: 'Financial',
    tenders: 'ADS & Tender',
    news: 'News',
    contact: 'Contact Us',
    complaints: 'Complaints',
    
    // Hero Section
    heroSubtitle: 'Sinai Manganese Co. is the first and the largest producer of manganese ore in Egypt.',
    heroTitle: 'Sinai Manganese Co.',
    heroDescription:
      'Sinai Manganese Co. (SMC) was founded on May 18th 1957 to exploit the manganese deposits in the Sinai Peninsula. We operate the region’s only 36,000 MTPA electric furnace along with a 21 MW gas turbine power station.',
    heroPrimaryCta: 'Contact us',
    heroSecondaryCta: 'Discover our history',
    awardTitle: 'Awarded quality',
    awardDescription:
      'Our products are manufactured and rigorously tested to the highest international standards so you can rely on consistent ferroalloy performance.',
    
    // Stats
    statExperienceLabel: 'Years of experience',
    statExperienceDescription: 'We have more than 30 years of expertise producing Silicomanganese.',
    statWorkersLabel: 'Our workers',
    statWorkersDescription: 'Over 500 skilled employees power our furnaces, port, and logistics.',
    statProductionLabel: 'Annual production',
    statProductionDescription: 'We produce 36 thousand tons of Silicomanganese every year.',

    // Uses
    usesTitle: 'Uses of Silicomanganese',
    usesSubtitle: 'Versatile ferroalloys for critical industries',
    usesSteelTitle: 'Steel industry',
    usesSteelDescription: 'Silicomanganese is used as a deoxidizer and alloying agent.',
    usesChemicalTitle: 'Chemical industry',
    usesChemicalDescription: 'Influences the properties of the final chemical product.',
    usesWeldingTitle: 'Welding & separation',
    usesWeldingDescription: 'Powder applications in welding consumables and mineral separation.',

    // Energy & Lifestyle Solutions
    energyTitle: 'Energy solutions',
    energySubtitle: 'Expanding into integrated solar and green power systems.',
    energyChargeTitle: 'Charge electric vehicles',
    energyChargeDescription: 'Charge your e-car with clean energy from your own roof and save money.',
    energyHeatingTitle: 'Solar powered heating',
    energyHeatingDescription: 'Around 30% of home energy consumption goes to heating and hot water.',
    energyRoofTitle: 'Energy on the roof',
    energyRoofDescription: 'High-quality solar modules deliver dependable power for decades.',

    // About
    aboutTitle: 'About us',
    aboutDescription:
      'SMC produces both high and low grades of manganese ore and operates an electrical furnace at Abu-Zinima, Sinai. We are the only Middle Eastern producer of Silicomanganese with our own 21 MW gas turbine power station.',

    // Contact
    contactSectionTitle: 'Contact us',
    contactSectionSubtitle: 'Feel free to leave us a message and we will get back shortly.',
    contactHeadOfficeLabel: 'Head office',
    contactHeadOfficeValue: 'Abu Zenima – South Sinai, Egypt',
    contactCairoOfficeLabel: 'Cairo office',
    contactCairoOfficeValue: '1 Kasr El-Nile St., Cairo – Egypt',
    contactPhoneLabel: 'Phone numbers',
    contactPhoneValue: '25740005 / 25740217 / 257401096 / 25764458 / 2579429 / 00201282055059 / 00201099899572 / 00201099899389',
    contactEmailLabel: 'Email',
    contactEmailValue: 'info@smc-eg.com',
    contactFormFirstName: 'First name*',
    contactFormLastName: 'Last name*',
    contactFormEmail: 'Email address*',
    contactFormPhone: 'Phone number',
    contactFormMessage: 'Message',
    contactFormSubmit: 'Send Message',
    contactHeroBody: 'Share your industrial ambitions and our partnerships team will respond within one business day to plan a tailored working session.',
    contactHighlight1Title: '21 MW',
    contactHighlight1Subtitle: 'Private power station',
    contactHighlight2Title: '36K TON',
    contactHighlight2Subtitle: 'Silicomanganese output',
    contactHighlight3Title: '1957',
    contactHighlight3Subtitle: 'Founded in Egypt',
    contactFormSectionLabel: 'Engage',
    contactFormTitle: 'Send us a direct brief',
    contactFactoryLabel: 'Plant location',
    contactFactoryTitle: 'Abu Zenima Industrial Complex',
    contactFactoryDescription: 'Site visits, investor meetings, and training sessions can be scheduled through our strategic relations desk.',
    contactProcessTitle: 'What happens after you submit?',
    contactProcessStep1: 'We respond within a business day to confirm context.',
    contactProcessStep2: 'We arrange a discovery workshop with your team (onsite or remote).',
    contactProcessStep3: 'We craft an initial roadmap detailing timelines, squads, and governance.',

    // Legacy keys reused elsewhere
    contactUs: 'Contact Us',
    footerDescription: 'Sinai Manganese Co. is the first and largest manganese ore producer in Egypt.',
    quickLinks: 'Useful links',
    followUs: 'Follow our social media',
    allRightsReserved: 'All Rights Reserved.',

    // Financial Page
    financialSubtitle: 'Maintaining strong financial performance through operational excellence and strategic growth',
    totalRevenue: 'Total Revenue',
    netProfit: 'Net Profit',
    exportVolume: 'Export Volume',
    productionEfficiency: 'Production Efficiency',
    marketShare: 'Market Share',
    growthRate: 'Growth Rate',
    revenue: 'Revenue',
    profit: 'Profit',
    production: 'Production',
    target: 'Target',
    expenses: 'Expenses',
    revenueDescription: 'Total annual revenue from all operations',
    profitDescription: 'Net profit after all expenses',
    exportDescription: 'Percentage of production exported globally',
    efficiencyDescription: 'Overall operational efficiency rating',
    marketShareDescription: 'Leading position in Egyptian manganese market',
    growthDescription: 'Year-over-year growth rate',
    revenueGrowth: 'Revenue Growth (5 Years)',
    revenueGrowthDescription: 'Steady growth in revenue and profitability over the past five years',
    productionPerformance: 'Monthly Production vs Target',
    productionPerformanceDescription: 'Production performance compared to monthly targets',
    exportDistribution: 'Export Distribution',
    exportDistributionDescription: 'Geographic distribution of exports by region',
    exportEurope: 'Europe',
    exportAsia: 'Asia',
    exportMiddleEast: 'Middle East',
    exportAfrica: 'Africa',
    quarterlyPerformance: 'Quarterly Performance',
    quarterlyPerformanceDescription: 'Revenue, expenses, and profit breakdown by quarter',
    investmentBreakdown: 'Investment Breakdown',
    investmentBreakdownDescription: 'Distribution of investments across different categories',
    investmentInfrastructure: 'Infrastructure',
    investmentTechnology: 'Technology',
    investmentSustainability: 'Sustainability',
    investmentResearch: 'Research & Development',
    efficiencyMetrics: 'Operational Efficiency Metrics',
    efficiencyMetricsDescription: 'Key performance indicators across different operational areas',
    efficiencyProduction: 'Production Efficiency',
    efficiencyQuality: 'Quality Control',
    efficiencyEnergy: 'Energy Efficiency',
    efficiencyLogistics: 'Logistics & Supply Chain',
    jan: 'Jan',
    feb: 'Feb',
    mar: 'Mar',
    apr: 'Apr',
    may: 'May',
    jun: 'Jun',

    // Products Section
    productsSectionLabel: 'Our Products',
    productsSectionTitle: 'High-Quality Industrial & Mining Products',
    productsSectionSubtitle: 'Comprehensive range of premium products manufactured to international standards',
    industrialProductsDescription: 'Advanced industrial products for various manufacturing applications',
    miningProductsDescription: 'Premium raw materials extracted and processed from our mining operations',
    productSilicomanganese: 'Silicomanganese',
    productSilicomanganeseDesc: 'High-quality ferroalloy used in steel production as a deoxidizer and alloying agent. Produced in our 36,000 MTPA electric furnace.',
    viewAllProducts: 'View All Products',
    backToProducts: 'Back to Products',
    backToNews: 'Back to News',
    specifications: 'Specifications',
    viewAllNews: 'View All News',

    // Dashboard
    dashboard: 'Dashboard',
    dashboardSubtitle: 'Manage your website content and data',
    settings: 'Settings',
    totalProducts: 'Total Products',
    totalNews: 'Total News',
    totalContacts: 'Total Contacts',
    totalComplaints: 'Total Complaints',
    overview: 'Overview',
    contacts: 'Contacts',
    recentActivity: 'Recent Activity',
    quickStats: 'Quick Stats',
    search: 'Search',
    addProduct: 'Add Product',
    addNews: 'Add News',
    name: 'Name',
    category: 'Category',
    views: 'Views',
    status: 'Status',
    actions: 'Actions',
    title: 'Title',
    date: 'Date',
    login: 'Login',
    logout: 'Logout',
    adminLogin: 'Admin Login',
    loginDescription: 'Sign in to access the dashboard',
    emailPlaceholder: 'admin@smc-eg.com',
    passwordPlaceholder: 'Enter your password',
    loggingIn: 'Logging in...',
    loginSuccess: 'Login successful!',
    loginError: 'Invalid email or password',
    adminAccessRequired: 'Admin access required',
    statistics: 'Statistics',
    pageContent: 'Page Content',
    heroBanners: 'Hero Banners',
    mediaLibrary: 'Media Library',
    manageProducts: 'Manage all products',
    manageNews: 'Manage all news articles',
    manageUsers: 'Manage users and permissions',
    manageMedia: 'Manage all media files',
    manageHeroBanners: 'Manage hero section banners',
    editPageContent: 'Edit content for all pages',
    manageSiteSettings: 'Manage website settings',
    viewAnalytics: 'View website analytics and statistics',
    manageContacts: 'Manage contact messages',
    manageComplaints: 'Manage customer complaints',
    editProduct: 'Edit Product',
    editNews: 'Edit News',
    addUser: 'Add User',
    editUser: 'Edit User',
    addBanner: 'Add Banner',
    editBanner: 'Edit Banner',
    uploadMedia: 'Upload Media',
    uploadImage: 'Upload Image',
    productsList: 'Products List',
    newsList: 'News List',
    usersList: 'Users List',
    contactsList: 'Contacts List',
    complaintsList: 'Complaints List',
    description: 'Description',
    subtitle: 'Subtitle',
    order: 'Order',
    active: 'Active',
    image: 'Image',
    content: 'Content',
    message: 'Message',
    saveAll: 'Save All',
    selectPage: 'Select Page',
    general: 'General',
    generalSettings: 'General Settings',
    contactInformation: 'Contact Information',
    siteName: 'Site Name',
    headOffice: 'Head Office',
    cairoOffice: 'Cairo Office',
    permissions: 'Permissions',
    role: 'Role',
    cancel: 'Cancel',
    save: 'Save',
    users: 'Users',
    email: 'Email',
    password: 'Password',
    phone: 'Phone',
    socialMedia: 'Social Media',
    seoSettings: 'SEO Settings',
    productImage: 'Product Image',
    changeImage: 'Change Image',
    imageUploadHint: 'Recommended: 800x600px, Max 2MB',
    addField: 'Add Field',
    chatMessages: 'Chat Messages',
    messagesList: 'Messages List',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    liveChat: 'Live Chat',
    pleaseFillAllFields: 'Please fill all fields',
    infoSaved: 'Info saved',
    enterYourName: 'Enter your name',
    enterYourEmail: 'Enter your email',
    startChat: 'Start Chat',
    noMessagesYet: 'No messages yet',
    typeYourMessage: 'Type your message...',
    adminResponseMessage: 'Thank you for your message. We will get back to you soon.',
    contactSubtitle: 'Get in touch',
    pageNotFound: 'Oops! Page not found',
    returnToHome: 'Return to Home',
    salesNumbers: 'Sales Numbers',
    administrationNumbers: 'Administration Numbers',
    forComplaints: 'For Complaints',
    since1957: 'Since 1957',
    designedBy: 'Designed by',
    facebook: 'Facebook',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    loading: 'Loading...',
    activeProducts: 'Active products',
    publishedArticles: 'Published articles',
    newMessages: 'New messages',
    pendingLabel: 'Pending',
    newContactReceived: 'New contact received',
    productUpdated: 'Product updated',
    newNewsPublished: 'New news article published',
    twoHoursAgo: '2 hours ago',
    fiveHoursAgo: '5 hours ago',
    oneDayAgo: '1 day ago',
    monthlyGrowth: 'Monthly Growth',
    totalViewsLabel: 'Total Views',
    smcAdmin: 'SMC Admin',
    controlPanel: 'Control Panel',
    productCategories: 'Product Categories',
    members: 'Members',
    clients: 'Clients',
    roleAdmin: 'Admin',
    roleEditor: 'Editor',
    roleViewer: 'Viewer',
    inactive: 'Inactive',
    loadingUsers: 'Loading users...',
    saving: 'Saving...',
    workingHours: 'Working Hours',
    workingHoursValue: 'Sun - Thu · 8:00 AM - 5:00 PM',
    manageSeoSettings: 'Manage SEO meta tags and settings',
    basicSeo: 'Basic SEO',
    socialMediaTab: 'Social Media',
    advancedTab: 'Advanced',
    pageTitleLabel: 'Page Title',
    titleEnglish: 'Title (English)',
    titleArabic: 'Title (Arabic)',
    metaDescriptionLabel: 'Meta Description',
    descriptionEnglish: 'Description (English)',
    descriptionArabic: 'Description (Arabic)',
    keywordsLabel: 'Keywords',
    keywordsEnglish: 'Keywords (English) - Comma separated',
    keywordsArabic: 'Keywords (Arabic)',
    openGraphLabel: 'Open Graph (Facebook, LinkedIn)',
    ogTitleEnglish: 'OG Title (English)',
    ogTitleArabic: 'OG Title (Arabic)',
    ogDescriptionEnglish: 'OG Description (English)',
    ogDescriptionArabic: 'OG Description (Arabic)',
    ogImageUrl: 'OG Image URL',
    twitterCardLabel: 'Twitter Card',
    twitterCardType: 'Twitter Card Type',
    twitterSiteLabel: 'Twitter Site',
    advancedSeo: 'Advanced SEO',
    canonicalUrlLabel: 'Canonical URL',
    robotsMetaLabel: 'Robots Meta',
    authorLabel: 'Author',
    languageLabel: 'Language',
    seoSavedSuccess: 'SEO settings saved successfully',
    readMore: 'Read More',
    loadingNews: 'Loading news...',
    newsPageSubtitle: 'Stay updated with the latest news and developments from Sinai Manganese Company',
    clientsSectionLabel: 'Our Clients',
    clientsSectionTitle: 'Our Success Partners',
    clientsSectionDescription: 'We are proud of our partnerships with industry-leading companies',
    companyIntroduction: 'Company Introduction',
    companyVision: 'Company Vision',
    companyHistory: 'Company History',

    send: 'Send Message',
    submit: 'Submit',
    all: 'All',
    phoneAndFaxNumbers: 'Phone & Fax Numbers',
    contactMessageSuccess: 'Message sent successfully! We will get back to you soon.',
    boardMembersTitle: 'Board Members',
    boardMembersSubtitle:
      'We are proud of our distinguished leadership of experts and professionals who lead Sinai Manganese Company towards excellence and success',
    noMembersAvailable: 'No members available at the moment',
    membersGovernanceNote: 'We are committed to transparency and good governance in all our operations',
    filterByCategory: 'Filter by category',
    showingProducts: 'Showing {count} products',
    noProductsFound: 'No products found',
    noProductsFoundCategory: 'No products are available for this category at the moment.',
    noCategoriesAvailable: 'No categories available',
    productsEyebrow: 'Products',
    ourProductsHeading: 'Our Products',
    productsPageIntro: 'Explore our products through a single tabbed view with a quick category filter.',
    categoryNotFound: 'Category not found',
    noProductsYet: 'No Products Yet',
    noProductsYetDesc: 'No products have been added to the {category} category yet. Check back later.',
    discoverProductsIn: 'Discover our products in {category}',
    productsHeading: 'Products',
    loadingProducts: 'Loading products...',
    productNotFound: 'Product Not Found',
    productNotFoundDesc: "The product you're looking for doesn't exist in the database.",
    imageGallery: 'Image Gallery',
    loadingProduct: 'Loading product...',
    noClientLogosAvailable: 'No client logos available at the moment',
    usesSectionDescription: 'Versatile ferroalloys for critical industries',
    aboutFeatureModernFacilities: 'Modern Facilities',
    aboutFeatureModernFacilitiesDesc: '36,000 MTPA electrical furnace at Abu-Zinima Sinai, Egypt',
    aboutFeaturePowerStation: 'Power Station',
    aboutFeaturePowerStationDesc: 'Own gas turbine power station producing 21 MW',
    aboutFeatureEmployees: '500+ Employees',
    aboutFeatureEmployeesDesc: 'Skilled workforce dedicated to excellence',
    aboutFeatureIndustryLeader: 'Industry Leader',
    aboutFeatureIndustryLeaderDesc: 'First and largest manganese ore producer in Egypt',
    aboutHistoryParagraph1:
      'Founded on May 18th, 1957, Sinai Manganese Company was established to exploit the manganese deposits in Sinai Peninsula, Egypt. From the beginning, our mission has been to provide high-quality manganese ore and silicomanganese to industries across Egypt and the Middle East.',
    aboutHistoryParagraph2:
      "Over the decades, we have grown to become Egypt's premier manganese producer, with state-of-the-art facilities and a commitment to quality that has earned us recognition both nationally and internationally.",
    aboutHistoryParagraph3:
      'Today, SMC operates a 36,000 MTPA electrical furnace and maintains its own 21 MW gas turbine power station, making us completely self-sufficient in our production capabilities. We are proud to be the only producer of Silicomanganese ferroalloy in the Middle East.',
    privatePortSubtitle:
      'Our private port facility ensures efficient and reliable export of our products to customers worldwide',
    portFeatureModernFacilities: 'Modern Facilities',
    portFeatureModernFacilitiesDesc:
      'State-of-the-art port facilities equipped for efficient loading and shipping operations',
    portFeatureHighCapacity: 'High Capacity',
    portFeatureHighCapacityDesc:
      'Capable of handling large volumes of manganese ore and silicomanganese shipments',
    portFeatureStrategicLocation: 'Strategic Location',
    portFeatureStrategicLocationDesc: 'Located at Abu-Zinima for optimal access to international shipping routes',
    portFeatureSafetyStandards: 'Safety Standards',
    portFeatureSafetyStandardsDesc: 'Strict adherence to international safety and environmental regulations',
    portCapabilities: 'Port Capabilities',
    portLoadingShipping: 'Loading & Shipping',
    portStorageHandling: 'Storage & Handling',
    portLoadingItem1: 'Direct loading to vessels with minimal handling',
    portLoadingItem2: 'Multiple loading points for efficient operations',
    portLoadingItem3: '24/7 operational capability',
    portLoadingItem4: 'Advanced weighing and quality control systems',
    portStorageItem1: 'Covered storage facilities to protect products',
    portStorageItem2: 'Segregated storage areas for different grades',
    portStorageItem3: 'Modern material handling equipment',
    portStorageItem4: 'Dust suppression systems',
    tendersSubtitle: 'Current tenders and procurement opportunities',
    tenderGuidelinesTitle: 'Tender Guidelines',
    tenderGuidelinesText:
      'All interested parties must submit complete documentation before the specified deadline. Late submissions will not be accepted. For detailed tender documents and submission requirements, please contact our procurement department.',
    loadingTenders: 'Loading tenders...',
    deadlineLabel: 'Deadline: ',
    downloadTenderDocument: 'Download Tender Document',
    submitProposal: 'Submit Proposal',
    noActiveTenders: 'No active tenders at the moment',
    needMoreInformation: 'Need More Information?',
    needMoreInformationDesc:
      'For tender inquiries, clarifications, or submission guidelines, please contact our procurement team',
    submitTenderProposal: 'Submit Tender Proposal',
    companyNameLabel: 'Company Name',
    contactNameLabel: 'Contact Name',
    attachedFilesLabel: 'Attached Files',
    chooseFiles: 'Choose Files',
    attachAtLeastOneFile: 'Please attach at least one file',
    submissionSentSuccess: 'Submission sent successfully',
    submissionFailed: 'Failed to submit',
    noNewsYet: 'No News Yet',
    noNewsYetDesc: 'No news have been published yet. Check back later for the latest updates.',
    customerRelationsTeam: 'Customer relations team',
    abuZinimaCairo: 'Abu-Zinima • Cairo',
    complaintsBadge: 'Complaints desk',
    complaintsTitle: 'Customer Complaints Center',
    complaintsDescription:
      'Listening is part of our manufacturing excellence. Share your concern and a service specialist will reach out within one business day.',
    complaintsStat1Label: 'Average response time',
    complaintsStat1Value: '< 24 hrs',
    complaintsStat2Label: 'Post-resolution satisfaction',
    complaintsStat2Value: '92%',
    complaintsStat3Label: 'Support squads',
    complaintsStat3Value: '3 dedicated teams',
    complaintsFormTitle: 'Submit a complaint',
    complaintsFormSubtitle: 'Complete the form and we will assign a case manager.',
    complaintsFormName: 'Full name',
    complaintsFormEmail: 'Work email',
    complaintsFormPhone: 'Phone number',
    complaintsFormTicket: 'Order / Contract ID (optional)',
    complaintsFormCategory: 'Complaint type',
    complaintsFormMessage: 'Describe the issue',
    complaintsFormSubmit: 'Send complaint',
    complaintCategoryQuality: 'Product quality',
    complaintCategoryDelivery: 'Delivery & logistics',
    complaintCategoryBilling: 'Billing & payment',
    complaintCategoryOther: 'Other',
    complaintsToastTitle: 'Complaint received',
    complaintsToastDescription: 'Our team will reach out within 24 working hours with next steps.',
    complaintsStepsTitle: 'How the process works',
    complaintsStep1Title: 'Ticket creation',
    complaintsStep1Desc: 'We log every detail and attach your documents to a digital case.',
    complaintsStep2Title: 'Direct follow-up',
    complaintsStep2Desc: 'A representative contacts you to clarify priority and expectations.',
    complaintsStep3Title: 'Resolution & recap',
    complaintsStep3Desc: 'We close the ticket after solving it and share a summary report.',
    complaintsHotlineTitle: 'Emergency hotline',
    complaintsHotlineNote: 'Available Sunday–Thursday, 8:00 AM – 10:00 PM.',
    complaintsSlaTitle: 'SLA',
    complaintsSlaNote: 'We commit to first responses within working hours and fast-track urgent cases.',
    complaintsAttachNote: 'You can attach photos or files after submission via the confirmation email.',
    postNotFound: 'Post Not Found',
    postNotFoundDesc: "The post you're looking for doesn't exist.",
    loadingPost: 'Loading post...',
  },
  ar: {
    home: 'الرئيسية',
    about: 'من نحن',
    products: 'المنتجات',
    industrialProducts: 'المنتجات الصناعية',
    miningProducts: 'منتجات التعدين',
    privatePort: 'الميناء الخاص',
    financial: 'المالية',
    tenders: 'الإعلانات والمناقصات',
    news: 'الأخبار',
    contact: 'اتصل بنا',
    complaints: 'شكاوى العملاء',

    heroSubtitle: 'شركة سيناء للمنجنيز هي الأولى والأكبر في إنتاج خام المنجنيز في مصر.',
    heroTitle: 'شركة سيناء للمنجنيز',
    heroDescription:
      'تأسست شركة سيناء للمنجنيز في 18 مايو 1957 لاستغلال رواسب المنجنيز في شبه جزيرة سيناء. ندير الفرن الكهربائي الوحيد في المنطقة بطاقة 36 ألف طن سنويًا إلى جانب محطة غازية بقدرة 21 ميجاوات.',
    heroPrimaryCta: 'تواصل معنا',
    heroSecondaryCta: 'اكتشف تاريخنا',
    awardTitle: 'جودة معتمدة',
    awardDescription: 'نصنع منتجاتنا ونختبرها وفقًا لأعلى المعايير الدولية لتضمن أداءً متسقًا للسبائك الحديدية.',

    statExperienceLabel: 'سنوات الخبرة',
    statExperienceDescription: 'لدينا أكثر من 30 عامًا من الخبرة في إنتاج السيليكومنجنيز.',
    statWorkersLabel: 'فريق العمل',
    statWorkersDescription: 'أكثر من 500 موظف يديرون أفراننا وميناءنا ولوجستياتنا.',
    statProductionLabel: 'الإنتاج السنوي',
    statProductionDescription: 'ننتج 36 ألف طن من السيليكومنجنيز كل عام.',

    usesTitle: 'استخدامات السيليكومنجنيز',
    usesSubtitle: 'حلول متعددة للقطاعات الحيوية',
    usesSteelTitle: 'صناعة الصلب',
    usesSteelDescription: 'يستخدم كعامل إزالة الأكسدة وعامل صناعة السبائك.',
    usesChemicalTitle: 'الصناعة الكيميائية',
    usesChemicalDescription: 'التأثير على خصائص المنتج الكيميائي النهائي.',
    usesWeldingTitle: 'اللحام والفصل',
    usesWeldingDescription: 'يُستخدم في مواد اللحام وعملية الفصل المعدني.',

    energyTitle: 'حلول الطاقة',
    energySubtitle: 'نوسع نشاطنا إلى أنظمة الطاقة الشمسية والطاقة الخضراء المتكاملة.',
    energyChargeTitle: 'شحن المركبات الكهربائية',
    energyChargeDescription: 'اشحن سيارتك بالطاقة النظيفة من سطح منزلك ووفّر التكاليف.',
    energyHeatingTitle: 'تدفئة بالطاقة الشمسية',
    energyHeatingDescription: 'حوالي 30٪ من استهلاك الطاقة المنزلي يذهب للتدفئة والمياه.',
    energyRoofTitle: 'طاقة على السطح',
    energyRoofDescription: 'وحدات شمسية عالية الجودة تضمن طاقة موثوقة لعقود.',

    aboutTitle: 'من نحن',
    aboutDescription:
      'تنتج شركة سيناء للمنجنيز الدرجات العالية والمنخفضة من خام المنجنيز وتدير فرنًا كهربائيًا في أبو زنيمة، وهي المنتج الوحيد للسيليكومنجنيز في الشرق الأوسط مع محطة كهرباء خاصة بقدرة 21 ميجاوات.',

    contactSectionTitle: 'اتصل بنا',
    contactSectionSubtitle: 'لا تتردد في ترك رسالة وسنعاود الاتصال بك قريباً.',
    contactHeadOfficeLabel: 'المقر الرئيسي',
    contactHeadOfficeValue: 'أبو زنيمة – جنوب سيناء، مصر',
    contactCairoOfficeLabel: 'مكتب القاهرة',
    contactCairoOfficeValue: '1 شارع قصر النيل، القاهرة – مصر',
    contactPhoneLabel: 'أرقام الهاتف',
    contactPhoneValue: '25740005 / 25740217 / 257401096 / 25764458 / 2579429 / 00201282055059 / 00201099899572 / 00201099899389',
    contactEmailLabel: 'البريد الإلكتروني',
    contactEmailValue: 'info@smc-eg.com',
    contactFormFirstName: 'الاسم الأول*',
    contactFormLastName: 'الاسم الأخير*',
    contactFormEmail: 'البريد الإلكتروني*',
    contactFormPhone: 'رقم الهاتف',
    contactFormMessage: 'الرسالة',
    contactFormSubmit: 'أرسل الرسالة',
    contactHeroBody: 'شاركنا أهدافك الصناعية وسيتواصل معك فريق الشراكات خلال يوم عمل واحد لترتيب جلسة عمل مخصصة.',
    contactHighlight1Title: '21 ميجاوات',
    contactHighlight1Subtitle: 'محطة طاقة خاصة',
    contactHighlight2Title: '36 ألف طن',
    contactHighlight2Subtitle: 'طاقة إنتاج السيليكومنجنيز',
    contactHighlight3Title: '1957',
    contactHighlight3Subtitle: 'عام التأسيس في مصر',
    contactFormSectionLabel: 'التواصل',
    contactFormTitle: 'أرسل موجزاً مباشراً',
    contactFactoryLabel: 'موقع المصنع',
    contactFactoryTitle: 'مجمع أبو زنيمة الصناعي',
    contactFactoryDescription: 'يمكن ترتيب جولات ميدانية واجتماعات المستثمرين وبرامج التدريب عبر فريق العلاقات الاستراتيجية لدينا.',
    contactProcessTitle: 'ماذا يحدث بعد الإرسال؟',
    contactProcessStep1: 'نتواصل خلال يوم عمل لتأكيد التفاصيل.',
    contactProcessStep2: 'نحدد جلسة استكشافية مع فريقك (حضوريًا أو عن بُعد).',
    contactProcessStep3: 'نصيغ خارطة طريق مبدئية تشمل الجدول الزمني والكوادر والحكومة.',

    contactUs: 'اتصل بنا',
    footerDescription: 'شركة سيناء للمنجنيز هي أول وأكبر منتج لخام المنجنيز في مصر.',
    quickLinks: 'روابط مفيدة',
    followUs: 'تابعنا على وسائل التواصل',
    allRightsReserved: 'جميع الحقوق محفوظة.',

    // Financial Page
    financialSubtitle: 'الحفاظ على أداء مالي قوي من خلال التميز التشغيلي والنمو الاستراتيجي',
    totalRevenue: 'إجمالي الإيرادات',
    netProfit: 'صافي الربح',
    exportVolume: 'حجم التصدير',
    productionEfficiency: 'كفاءة الإنتاج',
    marketShare: 'الحصة السوقية',
    growthRate: 'معدل النمو',
    revenue: 'الإيرادات',
    profit: 'الربح',
    production: 'الإنتاج',
    target: 'الهدف',
    expenses: 'المصروفات',
    revenueDescription: 'إجمالي الإيرادات السنوية من جميع العمليات',
    profitDescription: 'صافي الربح بعد جميع المصروفات',
    exportDescription: 'نسبة الإنتاج المصدر عالمياً',
    efficiencyDescription: 'تصنيف الكفاءة التشغيلية الإجمالية',
    marketShareDescription: 'المركز الرائد في سوق المنجنيز المصري',
    growthDescription: 'معدل النمو على أساس سنوي',
    revenueGrowth: 'نمو الإيرادات (5 سنوات)',
    revenueGrowthDescription: 'نمو مستمر في الإيرادات والربحية على مدى السنوات الخمس الماضية',
    productionPerformance: 'الإنتاج الشهري مقابل الهدف',
    productionPerformanceDescription: 'أداء الإنتاج مقارنة بالأهداف الشهرية',
    exportDistribution: 'توزيع الصادرات',
    exportDistributionDescription: 'التوزيع الجغرافي للصادرات حسب المنطقة',
    exportEurope: 'أوروبا',
    exportAsia: 'آسيا',
    exportMiddleEast: 'الشرق الأوسط',
    exportAfrica: 'أفريقيا',
    quarterlyPerformance: 'الأداء الربعي',
    quarterlyPerformanceDescription: 'تفصيل الإيرادات والمصروفات والربح حسب الربع',
    investmentBreakdown: 'تفصيل الاستثمارات',
    investmentBreakdownDescription: 'توزيع الاستثمارات عبر فئات مختلفة',
    investmentInfrastructure: 'البنية التحتية',
    investmentTechnology: 'التكنولوجيا',
    investmentSustainability: 'الاستدامة',
    investmentResearch: 'البحث والتطوير',
    efficiencyMetrics: 'مؤشرات الكفاءة التشغيلية',
    efficiencyMetricsDescription: 'مؤشرات الأداء الرئيسية عبر مجالات تشغيلية مختلفة',
    efficiencyProduction: 'كفاءة الإنتاج',
    efficiencyQuality: 'مراقبة الجودة',
    efficiencyEnergy: 'كفاءة الطاقة',
    efficiencyLogistics: 'اللوجستيات وسلسلة التوريد',
    jan: 'يناير',
    feb: 'فبراير',
    mar: 'مارس',
    apr: 'أبريل',
    may: 'مايو',
    jun: 'يونيو',

    // Products Section
    productsSectionLabel: 'منتجاتنا',
    productsSectionTitle: 'منتجات صناعية وتعدينية عالية الجودة',
    productsSectionSubtitle: 'مجموعة شاملة من المنتجات المميزة المصنعة وفقاً للمعايير الدولية',
    industrialProductsDescription: 'منتجات صناعية متقدمة لتطبيقات التصنيع المختلفة',
    miningProductsDescription: 'مواد خام مميزة مستخرجة ومعالجة من عمليات التعدين لدينا',
    productSilicomanganese: 'سيليكون منجنيز',
    productSilicomanganeseDesc: 'سبيكة حديدية عالية الجودة تستخدم في إنتاج الصلب كعامل إزالة الأكسدة وعامل صناعة السبائك. يتم إنتاجها في فرننا الكهربائي بطاقة 36,000 طن سنوياً.',
    viewAllProducts: 'عرض جميع المنتجات',
    backToProducts: 'العودة للمنتجات',
    backToNews: 'العودة للأخبار',
    specifications: 'المواصفات',
    viewAllNews: 'عرض جميع الأخبار',

    // Dashboard
    dashboard: 'لوحة التحكم',
    dashboardSubtitle: 'إدارة محتوى الموقع والبيانات',
    settings: 'الإعدادات',
    totalProducts: 'إجمالي المنتجات',
    totalNews: 'إجمالي الأخبار',
    totalContacts: 'إجمالي الاتصالات',
    totalComplaints: 'إجمالي الشكاوى',
    overview: 'نظرة عامة',
    contacts: 'الاتصالات',
    recentActivity: 'النشاط الأخير',
    quickStats: 'إحصائيات سريعة',
    search: 'بحث',
    addProduct: 'إضافة منتج',
    addNews: 'إضافة خبر',
    name: 'الاسم',
    category: 'الفئة',
    views: 'المشاهدات',
    status: 'الحالة',
    actions: 'الإجراءات',
    title: 'العنوان',
    date: 'التاريخ',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    adminLogin: 'تسجيل دخول الأدمن',
    loginDescription: 'سجل الدخول للوصول إلى لوحة التحكم',
    emailPlaceholder: 'admin@smc-eg.com',
    passwordPlaceholder: 'أدخل كلمة المرور',
    loggingIn: 'جاري تسجيل الدخول...',
    loginSuccess: 'تم تسجيل الدخول بنجاح!',
    loginError: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    adminAccessRequired: 'يتطلب صلاحيات المسؤول',
    statistics: 'الإحصائيات',
    pageContent: 'محتوى الصفحات',
    heroBanners: 'بنرات الهيرو',
    mediaLibrary: 'مكتبة الوسائط',
    manageProducts: 'إدارة جميع المنتجات',
    manageNews: 'إدارة جميع المقالات',
    manageUsers: 'إدارة المستخدمين والصلاحيات',
    manageMedia: 'إدارة جميع ملفات الوسائط',
    manageHeroBanners: 'إدارة بنرات قسم الهيرو',
    editPageContent: 'تعديل محتوى جميع الصفحات',
    manageSiteSettings: 'إدارة إعدادات الموقع',
    viewAnalytics: 'عرض إحصائيات وتحليلات الموقع',
    manageContacts: 'إدارة رسائل الاتصال',
    manageComplaints: 'إدارة شكاوى العملاء',
    editProduct: 'تعديل منتج',
    editNews: 'تعديل خبر',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل مستخدم',
    addBanner: 'إضافة بانر',
    editBanner: 'تعديل بانر',
    uploadMedia: 'رفع وسائط',
    uploadImage: 'رفع صورة',
    productsList: 'قائمة المنتجات',
    newsList: 'قائمة الأخبار',
    usersList: 'قائمة المستخدمين',
    contactsList: 'قائمة الاتصالات',
    complaintsList: 'قائمة الشكاوى',
    description: 'الوصف',
    subtitle: 'العنوان الفرعي',
    order: 'الترتيب',
    active: 'نشط',
    image: 'صورة',
    content: 'المحتوى',
    message: 'الرسالة',
    saveAll: 'حفظ الكل',
    selectPage: 'اختر الصفحة',
    general: 'عام',
    generalSettings: 'الإعدادات العامة',
    contactInformation: 'معلومات الاتصال',
    siteName: 'اسم الموقع',
    headOffice: 'المكتب الرئيسي',
    cairoOffice: 'مكتب القاهرة',
    permissions: 'الصلاحيات',
    role: 'الدور',
    cancel: 'إلغاء',
    save: 'حفظ',
    users: 'المستخدمون',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    phone: 'الهاتف',
    socialMedia: 'وسائل التواصل',
    seoSettings: 'إعدادات SEO',
    productImage: 'صورة المنتج',
    changeImage: 'تغيير الصورة',
    imageUploadHint: 'موصى به: 800×600 بكسل، بحد أقصى 2 ميجابايت',
    addField: 'إضافة حقل',
    chatMessages: 'رسائل الدردشة',
    messagesList: 'قائمة الرسائل',
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    liveChat: 'الدردشة المباشرة',
    pleaseFillAllFields: 'يرجى ملء جميع الحقول',
    infoSaved: 'تم حفظ البيانات',
    enterYourName: 'أدخل اسمك',
    enterYourEmail: 'أدخل بريدك الإلكتروني',
    startChat: 'بدء المحادثة',
    noMessagesYet: 'لا توجد رسائل بعد',
    typeYourMessage: 'اكتب رسالتك...',
    adminResponseMessage: 'شكراً لرسالتك. سنتواصل معك قريباً.',
    contactSubtitle: 'تواصل معنا',
    pageNotFound: 'عذراً! الصفحة غير موجودة',
    returnToHome: 'العودة للرئيسية',
    salesNumbers: 'أرقام المبيعات',
    administrationNumbers: 'أرقام الإدارة',
    forComplaints: 'للشكاوى',
    since1957: 'منذ 1957',
    designedBy: 'صمم بواسطة',
    facebook: 'فيسبوك',
    whatsapp: 'واتساب',
    linkedin: 'لينكدإن',
    loading: 'جاري التحميل...',
    activeProducts: 'منتجات نشطة',
    publishedArticles: 'مقالات منشورة',
    newMessages: 'رسائل جديدة',
    pendingLabel: 'قيد الانتظار',
    newContactReceived: 'تم استلام رسالة اتصال جديدة',
    productUpdated: 'تم تحديث منتج',
    newNewsPublished: 'تم نشر مقال جديد',
    twoHoursAgo: 'منذ ساعتين',
    fiveHoursAgo: 'منذ 5 ساعات',
    oneDayAgo: 'منذ يوم',
    monthlyGrowth: 'النمو الشهري',
    totalViewsLabel: 'إجمالي المشاهدات',
    smcAdmin: 'إدارة SMC',
    controlPanel: 'لوحة التحكم',
    productCategories: 'أقسام المنتجات',
    members: 'الأعضاء',
    clients: 'العملاء',
    roleAdmin: 'مدير',
    roleEditor: 'محرر',
    roleViewer: 'مشاهد',
    inactive: 'غير نشط',
    loadingUsers: 'جاري تحميل المستخدمين...',
    saving: 'جاري الحفظ...',
    workingHours: 'ساعات العمل',
    workingHoursValue: 'الأحد - الخميس · 8:00 صباحاً - 5:00 مساءً',
    manageSeoSettings: 'إدارة وسوم SEO والإعدادات',
    basicSeo: 'SEO أساسي',
    socialMediaTab: 'وسائل التواصل',
    advancedTab: 'متقدم',
    pageTitleLabel: 'عنوان الصفحة',
    titleEnglish: 'العنوان (إنجليزي)',
    titleArabic: 'العنوان (عربي)',
    metaDescriptionLabel: 'الوصف التعريفي',
    descriptionEnglish: 'الوصف (إنجليزي)',
    descriptionArabic: 'الوصف (عربي)',
    keywordsLabel: 'الكلمات المفتاحية',
    keywordsEnglish: 'الكلمات المفتاحية (إنجليزي) - مفصولة بفواصل',
    keywordsArabic: 'الكلمات المفتاحية (عربي)',
    openGraphLabel: 'Open Graph (فيسبوك، لينكدإن)',
    ogTitleEnglish: 'عنوان OG (إنجليزي)',
    ogTitleArabic: 'عنوان OG (عربي)',
    ogDescriptionEnglish: 'وصف OG (إنجليزي)',
    ogDescriptionArabic: 'وصف OG (عربي)',
    ogImageUrl: 'رابط صورة OG',
    twitterCardLabel: 'بطاقة تويتر',
    twitterCardType: 'نوع بطاقة تويتر',
    twitterSiteLabel: 'حساب تويتر',
    advancedSeo: 'SEO متقدم',
    canonicalUrlLabel: 'الرابط الأساسي',
    robotsMetaLabel: 'وسم Robots',
    authorLabel: 'المؤلف',
    languageLabel: 'اللغة',
    seoSavedSuccess: 'تم حفظ إعدادات SEO بنجاح',
    readMore: 'اقرأ المزيد',
    loadingNews: 'جاري تحميل الأخبار...',
    newsPageSubtitle: 'ابق على اطلاع بآخر الأخبار والتطورات من شركة سيناء للمنجنيز',
    clientsSectionLabel: 'عملاؤنا',
    clientsSectionTitle: 'شركاؤنا في النجاح',
    clientsSectionDescription: 'نفتخر بشراكاتنا مع الشركات الرائدة في الصناعة',
    companyIntroduction: 'التعريف بالشركة',
    companyVision: 'رؤية الشركة',
    companyHistory: 'تاريخ الشركة',

    send: 'إرسال الرسالة',
    submit: 'إرسال',
    all: 'الكل',
    phoneAndFaxNumbers: 'أرقام الهاتف والفاكس',
    contactMessageSuccess: 'تم إرسال الرسالة بنجاح! سنتواصل معك قريباً.',
    boardMembersTitle: 'أعضاء مجلس الإدارة',
    boardMembersSubtitle:
      'نفتخر بقيادة متميزة من الخبراء والمحترفين الذين يقودون شركة سيناء للمنجنيز نحو التميز والنجاح',
    noMembersAvailable: 'لا يوجد أعضاء متاحين حالياً',
    membersGovernanceNote: 'نلتزم بالشفافية والحوكمة الرشيدة في جميع عملياتنا',
    filterByCategory: 'تصفية حسب الفئة',
    showingProducts: 'عرض {count} منتجًا',
    noProductsFound: 'لا توجد منتجات',
    noProductsFoundCategory: 'لم يتم العثور على منتجات في هذا التصنيف في الوقت الحالي.',
    noCategoriesAvailable: 'لا توجد أقسام متاحة',
    productsEyebrow: 'المنتجات',
    ourProductsHeading: 'منتجاتنا',
    productsPageIntro: 'استكشف منتجاتنا من خلال تبويب واحد مع فلتر فئات سريع.',
    categoryNotFound: 'القسم غير موجود',
    noProductsYet: 'لا توجد منتجات بعد',
    noProductsYetDesc: 'لم يتم إضافة أي منتجات في فئة {category} حتى الآن. تحقق مرة أخرى لاحقاً.',
    discoverProductsIn: 'اكتشف منتجاتنا في {category}',
    productsHeading: 'المنتجات',
    loadingProducts: 'جاري تحميل المنتجات...',
    productNotFound: 'المنتج غير موجود',
    productNotFoundDesc: 'المنتج الذي تبحث عنه غير موجود في قاعدة البيانات.',
    imageGallery: 'معرض الصور',
    loadingProduct: 'جاري تحميل المنتج...',
    noClientLogosAvailable: 'لا توجد صور عملاء متاحة حالياً',
    usesSectionDescription: 'سبائك متعددة الاستخدامات للصناعات الحرجة',
    aboutFeatureModernFacilities: 'مرافق حديثة',
    aboutFeatureModernFacilitiesDesc: 'فرن كهربائي بطاقة 36,000 طن سنوياً في أبو زنيمة، سيناء، مصر',
    aboutFeaturePowerStation: 'محطة الطاقة',
    aboutFeaturePowerStationDesc: 'محطة طاقة غازية خاصة تنتج 21 ميجاوات',
    aboutFeatureEmployees: 'أكثر من 500 موظف',
    aboutFeatureEmployeesDesc: 'قوة عمل ماهرة مكرسة للتميز',
    aboutFeatureIndustryLeader: 'رائد الصناعة',
    aboutFeatureIndustryLeaderDesc: 'أول وأكبر منتج لخام المنجنيز في مصر',
    aboutHistoryParagraph1:
      'تأسست شركة سيناء للمنجنيز في 18 مايو 1957 لاستغلال رواسب المنجنيز في شبه جزيرة سيناء، مصر. منذ البداية، كانت مهمتنا توفير خام المنجنيز وسيليكون المنجنيز عالي الجودة للصناعات في جميع أنحاء مصر والشرق الأوسط.',
    aboutHistoryParagraph2:
      'على مر العقود، نمنا لتصبح الشركة الرائدة في إنتاج المنجنيز في مصر، مع مرافق حديثة والتزام بالجودة أكسبنا اعترافاً وطنياً ودولياً.',
    aboutHistoryParagraph3:
      'اليوم، تدير شركة سيناء للمنجنيز فرناً كهربائياً بطاقة 36,000 طن سنوياً وتحتفظ بمحطة طاقة غازية خاصة تنتج 21 ميجاوات، مما يجعلنا مكتفين ذاتياً تماماً في قدراتنا الإنتاجية. نحن فخورون بأن نكون المنتج الوحيد لسبائك سيليكون المنجنيز في الشرق الأوسط.',
    privatePortSubtitle:
      'تضمن منشأة الميناء الخاص لدينا تصديراً فعالاً وموثوقاً لمنتجاتنا للعملاء في جميع أنحاء العالم',
    portFeatureModernFacilities: 'مرافق حديثة',
    portFeatureModernFacilitiesDesc: 'مرافق ميناء حديثة مجهزة لعمليات التحميل والشحن الفعالة',
    portFeatureHighCapacity: 'قدرة عالية',
    portFeatureHighCapacityDesc: 'قادرة على التعامل مع أحجام كبيرة من شحنات خام المنجنيز وسيليكون المنجنيز',
    portFeatureStrategicLocation: 'موقع استراتيجي',
    portFeatureStrategicLocationDesc: 'يقع في أبو زنيمة للوصول الأمثل إلى طرق الشحن الدولية',
    portFeatureSafetyStandards: 'معايير السلامة',
    portFeatureSafetyStandardsDesc: 'الالتزام الصارم بمعايير السلامة والبيئة الدولية',
    portCapabilities: 'قدرات الميناء',
    portLoadingShipping: 'التحميل والشحن',
    portStorageHandling: 'التخزين والمعالجة',
    portLoadingItem1: 'تحميل مباشر على السفن مع أقل قدر من المناولة',
    portLoadingItem2: 'نقاط تحميل متعددة للعمليات الفعالة',
    portLoadingItem3: 'قدرة تشغيلية على مدار الساعة',
    portLoadingItem4: 'أنظمة وزن ومراقبة جودة متقدمة',
    portStorageItem1: 'منشآت تخزين مغطاة لحماية المنتجات',
    portStorageItem2: 'مناطق تخزين منفصلة للدرجات المختلفة',
    portStorageItem3: 'معدات معالجة مواد حديثة',
    portStorageItem4: 'أنظمة قمع الغبار',
    tendersSubtitle: 'المناقصات الحالية وفرص المشتريات',
    tenderGuidelinesTitle: 'إرشادات المناقصة',
    tenderGuidelinesText:
      'يجب على جميع الأطراف المهتمة تقديم الوثائق الكاملة قبل الموعد النهائي المحدد. لن يتم قبول التقديمات المتأخرة. للحصول على وثائق المناقصة التفصيلية ومتطلبات التقديم، يرجى الاتصال بقسم المشتريات لدينا.',
    loadingTenders: 'جاري تحميل المناقصات...',
    deadlineLabel: 'الموعد النهائي: ',
    downloadTenderDocument: 'تحميل وثيقة المناقصة',
    submitProposal: 'تقديم عرض',
    noActiveTenders: 'لا توجد مناقصات نشطة حالياً',
    needMoreInformation: 'تحتاج المزيد من المعلومات؟',
    needMoreInformationDesc:
      'للاستفسارات حول المناقصات أو التوضيحات أو إرشادات التقديم، يرجى الاتصال بفريق المشتريات لدينا',
    submitTenderProposal: 'تقديم عرض للمناقصة',
    companyNameLabel: 'اسم الشركة',
    contactNameLabel: 'اسم جهة الاتصال',
    attachedFilesLabel: 'الملفات المرفقة',
    chooseFiles: 'اختر الملفات',
    attachAtLeastOneFile: 'يرجى إرفاق ملف واحد على الأقل',
    submissionSentSuccess: 'تم إرسال التقديم بنجاح',
    submissionFailed: 'فشل في إرسال التقديم',
    noNewsYet: 'لا توجد أخبار بعد',
    noNewsYetDesc: 'لم يتم نشر أي أخبار حتى الآن. تحقق مرة أخرى لاحقاً للحصول على آخر التحديثات.',
    customerRelationsTeam: 'فريق علاقات العملاء',
    abuZinimaCairo: 'أبو زنيمة • القاهرة',
    complaintsBadge: 'مركز الشكاوى',
    complaintsTitle: 'منصة شكاوى العملاء',
    complaintsDescription:
      'نؤمن بأن الاستماع إلى عملائنا جزء من نجاحنا التشغيلي. شاركنا أي ملاحظة أو مشكلة وسيتواصل معك فريق خدمة العملاء خلال يوم عمل واحد.',
    complaintsStat1Label: 'متوسط وقت الاستجابة',
    complaintsStat1Value: '< 24 ساعة',
    complaintsStat2Label: 'مستوى الرضا بعد الإغلاق',
    complaintsStat2Value: '92%',
    complaintsStat3Label: 'فِرق الدعم',
    complaintsStat3Value: '3 فرق متخصصة',
    complaintsFormTitle: 'إرسال الشكوى',
    complaintsFormSubtitle: 'املأ النموذج التالي وسنقوم بتعيين مندوب متابعة للطلب.',
    complaintsFormName: 'الاسم الكامل',
    complaintsFormEmail: 'البريد الإلكتروني',
    complaintsFormPhone: 'رقم الهاتف',
    complaintsFormTicket: 'رقم الطلب أو العقد (اختياري)',
    complaintsFormCategory: 'نوع الشكوى',
    complaintsFormMessage: 'تفاصيل الشكوى',
    complaintsFormSubmit: 'إرسال الشكوى',
    complaintCategoryQuality: 'جودة المنتج',
    complaintCategoryDelivery: 'التسليم والخدمات اللوجستية',
    complaintCategoryBilling: 'الفواتير والمدفوعات',
    complaintCategoryOther: 'أخرى',
    complaintsToastTitle: 'تم استلام الشكوى',
    complaintsToastDescription: 'سنتواصل معك خلال 24 ساعة عمل لمتابعة التفاصيل.',
    complaintsStepsTitle: 'ماذا يحدث بعد الإرسال؟',
    complaintsStep1Title: 'فتح بطاقة شكوى',
    complaintsStep1Desc: 'يتم إنشاء بطاقة رقمية وربطها ببياناتك ومرفقاتك.',
    complaintsStep2Title: 'تواصل مباشر',
    complaintsStep2Desc: 'يتواصل معك أحد ممثلي خدمة العملاء لتأكيد التفاصيل وتحديد الأولويات.',
    complaintsStep3Title: 'حل ومراجعة',
    complaintsStep3Desc: 'يتم إغلاق الطلب بعد الحل ومشاركة تقرير ملخص بالنتائج.',
    complaintsHotlineTitle: 'خط ساخن للطوارئ',
    complaintsHotlineNote: 'متاح من الأحد إلى الخميس، 8 صباحًا - 10 مساءً.',
    complaintsSlaTitle: 'SLA',
    complaintsSlaNote: 'نلتزم برد أولي خلال ساعات العمل وأولوية قصوى للحالات الطارئة.',
    complaintsAttachNote: 'يمكنك إرفاق ملفات أو صور بعد إرسال الطلب عبر البريد الإلكتروني الذي يصلك.',
    postNotFound: 'المقال غير موجود',
    postNotFoundDesc: 'المقال الذي تبحث عنه غير موجود.',
    loadingPost: 'جاري تحميل المقال...',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const location = useLocation();
  const navigate = useNavigate();
  const params = useParams<{ lang?: string }>();
  
  // Get language from URL or default to 'en'
  const getLanguageFromUrl = (): Language => {
    const langFromUrl = params.lang || location.pathname.split('/')[1];
    return (langFromUrl === 'ar' || langFromUrl === 'en') ? langFromUrl : 'en';
  };

  const [language, setLanguage] = useState<Language>(getLanguageFromUrl());

  // Sync language with URL changes
  useEffect(() => {
    const urlLang = getLanguageFromUrl();
    if (urlLang !== language) {
      setLanguage(urlLang);
    }
  }, [location.pathname, params.lang]);

  // Update language and URL
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);

    if (typeof document !== 'undefined') {
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = lang;
    }

    const currentPath = location.pathname;

    if (currentPath.startsWith('/dashboard') || currentPath.startsWith('/login')) {
      return;
    }

    const newPath = buildLocalizedUrl(
      currentPath,
      lang as AppLanguage,
      location.search,
      location.hash,
    );

    if (newPath !== `${currentPath}${location.search}${location.hash}`) {
      navigate(newPath, { replace: true });
    }
  };

  useEffect(() => {
    // Update document direction based on language
    if (typeof document !== 'undefined') {
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
